# Generated by Django 4.2.25 on 2025-10-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=500)),
                ('fun_fact', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
