# Generated by Django 4.2.25 on 2025-10-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
    ]
