# Generated by Django 4.2.25 on 2025-10-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_pet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('friend', models.CharField(choices=[('Dug', 'Dug'), ('Roz', 'Roz'), ('Grandpa', 'Grandpa'), ('Spooky', 'Spooky'), ('Fig', 'Fig')], default=('Dug', 'Dug'), max_length=100)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.pet')),
            ],
        ),
    ]
